//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7_11_Slack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoria
    {
        public int IdSubCategoria { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string NombreSubCategoria { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
